theme: jekyll-theme-minimal
logo: https://static.wikia.nocookie.net/mspaintadventures/images/1/17/Karkat_Vantas.png/revision/latest/thumbnail/width/360/height/450?cb=20111216151555
title: Bioinformatics
